// This file was auto-generated by ML.NET Model Builder. 

using System;
using CCPPApplicationML.Model;

namespace CCPPApplicationML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Taxi_id = 85F,
                Trip_seconds = 180F,
                Trip_miles = 0.4F,
                Tips = 0F,
                Trip_total = 4.5F,
                Payment_type = 1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Fare with predicted Fare from sample data...\n\n");
            Console.WriteLine($"Taxi_id: {sampleData.Taxi_id}");
            Console.WriteLine($"Trip_seconds: {sampleData.Trip_seconds}");
            Console.WriteLine($"Trip_miles: {sampleData.Trip_miles}");
            Console.WriteLine($"Tips: {sampleData.Tips}");
            Console.WriteLine($"Trip_total: {sampleData.Trip_total}");
            Console.WriteLine($"Payment_type: {sampleData.Payment_type}");
            Console.WriteLine($"\n\nPredicted Fare: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
